// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD-7XLVntSO5riGkBKJ096xKYnXfBLl5Rg',
//     appId: '1:202996347888:web:c790682a77e838d4332335',
//     messagingSenderId: '202996347888',
//     projectId: 'userhub-e1b6e',
//     authDomain: 'userhub-e1b6e.firebaseapp.com',
//     storageBucket: 'userhub-e1b6e.firebasestorage.app',
//     measurementId: 'G-Y9LQMRM4TP',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBZT1B2FqKVnRP461ZqDN0pGv9vcde7wAs',
//     appId: '1:202996347888:android:7e9ecc23232a54b1332335',
//     messagingSenderId: '202996347888',
//     projectId: 'userhub-e1b6e',
//     storageBucket: 'userhub-e1b6e.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyApq06ivt3-AnmoWbiOf2setHRtUGKU5cI',
//     appId: '1:202996347888:ios:810b7f61a949ff81332335',
//     messagingSenderId: '202996347888',
//     projectId: 'userhub-e1b6e',
//     storageBucket: 'userhub-e1b6e.firebasestorage.app',
//     iosBundleId: 'com.example.personApp',
//   );
// }
